Remove unused "type: ignore" comment
The underlying problem here seems to have been fixed at some point,
since mypy complained:

  distributed/shuffle/_rechunk.py:756: error: Unused "type: ignore" comment  [unused-ignore]