Avoid easy deprecated calls to asyncio.get_event_loop() (#6170)
when using `asyncio.run` in `gen_test` test that later call `asyncio.get_event_loop()` fail - even before python3.10:


```python
import asyncio

async def amain():
    pass

asyncio.run(amain())
asyncio.get_event_loop()
```

```pytb
Traceback (most recent call last):
  File "foo.py", line 7, in <module>
    asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```

* use `gen_test` for tests that acquire `IOLoop.current()`
* use `get_running_loop()` instead of `get_event_loop()`
* use `asyncio.run()` instead of `asyncio.get_event_loop().run_until_complete()`

See https://github.com/dask/distributed/issues/6164