Add informative error message to install uvloop (#4664)
If you have a config value set to use uvloop but don't have uvloop
installed then things end badly, with a non-informative error message

This provides a more informative error message

```
RuntimeError: The distributed.admin.event-loop configuration value is set to 'uvloop' but the uvloop module is not installed

Please either change the config value or install one of the following
    conda install uvloop
    pip install uvloop
```