Fix bokeh error for `memory_limit=None`
Diagnostics page currently breaks if `memory_limit` is set to `None`.
```
distributed.utils - ERROR - '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/Users/brettnaul/venvs/model37/lib/python3.7/site-packages/distributed/utils.py", line 646, in log_errors
    yield
  File "/Users/brettnaul/venvs/model37/lib/python3.7/site-packages/distributed/bokeh/scheduler.py", line 337, in update
    if limit > max_limit:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
Maybe there's a more elegant way to do this? I'm not sure how to check if the `memory_limit` attr exists, I assume that's why it's currently done using a try/except